(function(){'use strict';
const CFG={apiKey:'AIzaSyAzr0B8M-8PeJwK0XAaHDapyLPzsvmTThY',authDomain:'ai-maura-06-26.firebaseapp.com',projectId:'ai-maura-06-26',appId:'1:279194148183:web:f96d4d94dff8c8d2c7b212'};
const BUCKET='ai-maura-06-26-facturas-gastos',ALLOW=['kenotractopartes@gmail.com','daniel@tractopartes.com'];
const $=id=>document.getElementById(id),esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!window.firebase||!firebase.auth||!firebase.storage){$('mensaje').textContent='No se pudo cargar la conexión. Revisa internet y vuelve a abrir esta página.';return}
let app;try{app=firebase.app('maura')}catch(e){app=firebase.initializeApp(CFG,'maura')}
const auth=app.auth(),storage=app.storage('gs://'+BUCKET);
let rows=[],marks={},visible=[],limit=30,epoch=0,current=null,loading=false,urls=[];
function text(s){$('mensaje').textContent=s}
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Monterrey',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function shift(day,n){let d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function range(){let t=today(),p=$('periodo').value,m=$('mes').value||t.slice(0,7);if(p==='todos')return['0000','9999'];if(p==='mes')m=t.slice(0,7);if(p==='mes'||p==='otro')return[m+'-01',m+'-31'];if(p==='rango')return[$('desde').value||'0000',$('hasta').value||'9999'];let d=new Date(t+'T12:00:00Z').getUTCDay(),a=shift(t,-((d+6)%7)-(p==='anterior'?7:0));return[a,shift(a,6)]}
function isPrinted(r){return marks[r.id]?marks[r.id].impreso===true:(r.ids_anteriores||[]).some(id=>marks[id]&&marks[id].impreso===true)}
async function pool(items,fn,n=5){let out=Array(items.length),i=0;await Promise.all(Array.from({length:Math.min(n,items.length)},async()=>{while(i<items.length){let j=i++;out[j]=await fn(items[j]);}}));return out}
async function blob(path){if(!/^(indice\.json|meses\/\d{4}-\d{2}\.json|originales\/[a-f0-9]{64}\.(pdf|xml)|control\/[a-z0-9-]+\.json)$/.test(path))throw Error('Ruta de archivo inválida');let u=auth.currentUser;if(!u)throw Error('Inicia sesión');let token=await u.getIdToken();let ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),30000);try{let r=await fetch('https://firebasestorage.googleapis.com/v0/b/'+BUCKET+'/o/'+encodeURIComponent(path)+'?alt=media',{headers:{Authorization:'Firebase '+token},cache:'no-store',signal:ctrl.signal});if(!r.ok)throw Error(r.status===403?'Esta cuenta no tiene acceso a las facturas.':r.status===404?'El archivo aún no está disponible.':'No se pudo abrir el archivo ('+r.status+').');return await r.blob()}finally{clearTimeout(timer)}}
async function json(path){return JSON.parse(await (await blob(path)).text())}
function fuenteHtml(f){let who=f.cuenta==='daniel@tractopartes.com'?'Papá':f.cuenta==='blanca@tractopartes.com'?'Blanca':'Eugenio';if(f.estado==='pendiente_conexion')return '<p class="pendiente"><b>'+esc(who)+':</b> falta conectar Gmail para recibir sus facturas automáticamente.</p>';let time=f.ultima_revision?new Date(f.ultima_revision).toLocaleString('es-MX',{timeZone:'America/Monterrey',dateStyle:'short',timeStyle:'short'}):'sin revisión completa';let stale=f.ultima_revision&&(Date.now()-Date.parse(f.ultima_revision)>2*3600000);return '<p class="'+(f.estado==='error'||stale?'pendiente':'')+'"><b>'+esc(who)+':</b> '+esc(f.cuenta)+' · última lectura '+esc(time)+(f.estado==='error'?' · lectura interrumpida; se conservan los documentos anteriores':stale?' · sin lectura reciente':f.pendientes?' · completando historial':f.avisos&&f.avisos.length?' · hay '+f.avisos.length+' adjuntos que requieren revisión':'')+'</p>'}
async function load(){if(loading)return;loading=true;let rev=++epoch,owner=auth.currentUser;current=owner;$('actualizar').disabled=true;text('Reuniendo los documentos…');try{let index=await json('indice.json');let batches=await pool(index.meses||[],m=>json('meses/'+m+'.json'));let controls=await storage.ref('control').listAll();let values=await pool(controls.items,r=>json(r.fullPath));if(rev!==epoch||auth.currentUser!==owner)return;rows=batches.flat();marks={};controls.items.forEach((r,i)=>{marks[r.name.replace(/\.json$/,'')]=values[i]});let sources=index.fuentes||[],attention=sources.some(f=>f.estado!=='al_dia'||!f.ultima_revision||Date.now()-Date.parse(f.ultima_revision)>2*3600000);$('fuentes').innerHTML='<details'+(attention?' open':'')+'><summary>'+sources.filter(f=>f.estado==='al_dia').length+' correos revisados · '+(attention?'ver estado':'ver última actualización')+'</summary>'+sources.map(fuenteHtml).join('')+'<p>Revisión de correos desde el 1 de septiembre de 2026.</p></details>';$('bandeja').hidden=false;$('actualizar').hidden=false;limit=30;text('');render()}catch(e){if(rev===epoch)text((e.name==='AbortError'?'La conexión tardó demasiado. Intenta Actualizar.':e.message==='Failed to fetch'?'No se pudo conectar con los documentos. Revisa internet e intenta Actualizar.':e.message)+' Tus documentos anteriores siguen conservados.')}finally{loading=false;$('actualizar').disabled=false;if(rev!==epoch&&auth.currentUser&&ALLOW.includes(auth.currentUser.email))load()}}
function render(){let [from,to]=range(),query=$('buscar').value.trim().toLocaleLowerCase(),state=$('estado').value;if(from>to){text('La fecha inicial debe ser anterior a la final.');return}text('');visible=rows.filter(r=>r.fecha>=from&&r.fecha<=to&&(!query||[r.empresa,r.folio,r.uuid,(r.fuentes||[]).map(x=>x.asunto).join(' ')].join(' ').toLocaleLowerCase().includes(query))).filter(r=>state==='todos'||state==='impreso'&&isPrinted(r)||state==='por_imprimir'&&!isPrinted(r)&&r.archivos.some(a=>a.tipo==='application/pdf')||state==='cfdi'&&r.clase==='factura'||state==='tarjeta'&&r.tarjeta==='8120'||r.estado===state).sort((a,b)=>b.fecha.localeCompare(a.fecha)||a.empresa.localeCompare(b.empresa));$('conteo').textContent=visible.length+' documento'+(visible.length===1?'':'s')+' en el periodo';$('mas').hidden=visible.length<=limit;$('lista').innerHTML=visible.length?visible.slice(0,limit).map(card).join(''):'<div class="vacio"><h2>No hay documentos en este filtro</h2><p>Prueba otro periodo o revisa el estado de los correos de arriba.</p></div>'}
function card(r){let printed=isPrinted(r),label=r.clase==='factura'?(r.tipo_cfdi==='P'?'Complemento de pago':r.tipo_cfdi==='E'?'Nota de crédito':'CFDI · RFC del negocio'):r.clase==='cargo'?'Cargo ••8120 · sin factura vinculada':r.estado==='sin_adjunto'?'Correo · falta adjunto':r.tarjeta==='8120'?'Factura / recibo · tarjeta ••8120':'Documento por revisar';let files=r.archivos||[],money=r.importe&&r.tipo_cfdi!=='P'?(Number.isFinite(Number(r.importe))?Number(r.importe).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2}):r.importe):'';return '<article class="registro" data-id="'+esc(r.id)+'"><div><span class="etiqueta '+(r.clase==='factura'?'':r.clase==='cargo'?'cargo':'revisar')+'">'+esc(label)+'</span><h2>'+esc(r.empresa)+'</h2><p class="meta">'+esc(r.fecha)+' · fecha de '+(r.fecha_tipo==='factura'?'factura':r.fecha_tipo==='recibo'?'recibo':'correo')+(r.folio?' · folio '+esc(r.folio):'')+'</p><div class="acciones">'+files.map((a,i)=>'<button class="archivo '+(a.tipo==='application/pdf'?'pdf':'')+'" data-file="'+i+'">'+(a.tipo==='application/pdf'?(a.rotulo==='recibo'?'Ver / imprimir recibo':'Ver / imprimir PDF'):'Descargar XML')+(files.filter(x=>x.tipo===a.tipo).length>1?' '+(i+1):'')+'</button>').join('')+(files.some(a=>a.tipo==='application/pdf')?'<button class="mini '+(printed?'impreso':'')+'" data-print="1">'+(printed?'✓ Impreso · desmarcar':'Ya lo imprimí')+'</button>':'')+'</div></div><div class="importe">'+(money?esc(money)+' <small>'+esc(r.moneda||'moneda por confirmar')+'</small>':'')+'</div><div class="detalle">'+esc(r.nota)+'<details><summary>Ver origen y archivos</summary>'+(r.fuentes||[]).map(f=>'<p><b>'+esc(f.cuenta)+'</b> · '+esc(f.remitente)+'<br>'+esc(f.asunto)+'<br>Recibido: '+esc(f.recibido.slice(0,10))+' · correo '+esc(f.uid)+'</p>').join('')+files.map(a=>'<p>'+esc(a.nombre)+' · '+Math.round(a.bytes/1024)+' KB</p>').join('')+(r.uuid?'<p>UUID: '+esc(r.uuid)+'</p>':'')+'</details></div></article>'}
$('lista').addEventListener('click',async e=>{let b=e.target.closest('button'),a=e.target.closest('[data-id]');if(!b||!a)return;let r=rows.find(x=>x.id===a.dataset.id);if(!r)return;b.disabled=true;let win=null;try{if(b.hasAttribute('data-file')){let f=r.archivos[Number(b.dataset.file)],isPDF=f.tipo==='application/pdf';if(isPDF){win=window.open('about:blank','_blank');if(win){win.opener=null;win.document.body.textContent='Preparando el PDF…'}}let data=await blob(f.ruta),url=URL.createObjectURL(new Blob([data],{type:f.tipo}));urls.push(url);if(isPDF&&win){win.location.href=url}else{let link=document.createElement('a');link.href=url;link.download=f.nombre;document.body.appendChild(link);link.click();link.remove()}text('')}else if(b.hasAttribute('data-print')){let mark={impreso:!isPrinted(r),actualizado:new Date().toISOString(),por:auth.currentUser.email};await storage.ref('control/'+r.id+'.json').putString(JSON.stringify(mark),'raw',{contentType:'application/json',cacheControl:'private,no-store'});marks[r.id]=mark;render();text(mark.impreso?'Marcado como impreso.':'Marca de impresión quitada.')}}catch(err){if(win)win.close();text('No se completó la acción: '+err.message)}finally{b.disabled=false}});
for(let id of ['periodo','mes','desde','hasta','estado'])$(id).addEventListener('change',()=>{let p=$('periodo').value;$('mes-caja').hidden=p!=='otro';$('desde-caja').hidden=$('hasta-caja').hidden=p!=='rango';limit=30;render()});$('buscar').addEventListener('input',()=>{limit=30;render()});$('mas').onclick=()=>{limit+=30;render()};$('actualizar').onclick=load;$('salir').onclick=()=>auth.signOut();
$('mes').value=today().slice(0,7);$('desde').value=today().slice(0,7)+'-01';$('hasta').value=today();
$('login-form').onsubmit=async e=>{e.preventDefault();let b=e.target.querySelector('button');b.disabled=true;try{await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);await auth.signInWithEmailAndPassword($('correo').value.trim(),$('clave').value);$('clave').value=''}catch(err){text('No se pudo iniciar sesión. Revisa tu correo, contraseña de la plataforma y conexión.')}finally{b.disabled=false}};
auth.onAuthStateChanged(u=>{epoch++;rows=[];marks={};visible=[];$('lista').innerHTML='';$('fuentes').innerHTML='';$('bandeja').hidden=true;urls.forEach(URL.revokeObjectURL);urls=[];if(!u){$('login').hidden=false;$('actualizar').hidden=true;text('');return}if(!ALLOW.includes(u.email)){ $('login').hidden=false;$('actualizar').hidden=true;text('Esta bandeja solo está habilitada para Eugenio y Daniel. Entra con una de esas cuentas.');return}$('login').hidden=true;$('sesion').textContent=u.email;load()});
})();
